### ISSUE TITLE
Inverted and Rotated half pyramid pattern

### ISSUE THREAD

**Issue by pranee17** [nazeer-18/java#10]
**Is your feature request related to a problem? Please describe.**
I've found an issue about patterns and would like to contribute for it

**Describe the solution you'd like**
If you assign this issue to me ,I'll add solution for Inverted and Rotated half pyramid Pattern in java language

**Describe alternatives you've considered**
I've already added some patterns so, I will ensure to follow the same structure for this pattern too

**Additional context**
    
![image](https://github.com/nazeer-18/java/assets/120731376/9ff0c233-2902-4cd6-b7ed-4a1a4f2ee574)
Sample pattern of Inverted and Rotated half pyramid  for n=5

**Comment by nazeer-18** [comment]
Great  you  can start working on it @pranee17 🙌
Assigned!

**Comment by pranee17** [comment]
completed🤗
