### ISSUE TITLE
Inverted half pyramid with numbers

### ISSUE THREAD

**Issue by pranee17** [nazeer-18/java#11]
**Is your feature request related to a problem? Please describe.**
I've found an issue about patterns and would like to contribute for it

**Describe the solution you'd like**
If you assign this issue to me ,I'll add solution for Inverted  half pyramid with numbers Pattern in java language

**Describe alternatives you've considered**
I've already added some patterns so, I will ensure to follow the same structure for this pattern too

**Additional context**
![image](https://github.com/nazeer-18/java/assets/120731376/cb9fa35e-c58c-4637-aa6c-6ed59b377330)

Sample pattern of Inverted half pyramid with numbers for n=6

**Comment by nazeer-18** [comment]
Assigned!! @pranee17

**Comment by pranee17** [comment]
completed
