### ISSUE TITLE
Floyd's Triangle Pattern

### ISSUE THREAD

**Issue by pranee17** [nazeer-18/java#12]
**Is your feature request related to a problem? Please describe.**
I've found an issue about patterns and would like to contribute for it

**Describe the solution you'd like**
If you assign this issue to me ,I'll add solution for Floyd's Triangle Pattern in java language

**Describe alternatives you've considered**
I've already added some patterns so, I will ensure to follow the same structure for this pattern too

**Additional context**
![image](https://github.com/nazeer-18/java/assets/120731376/404130ae-ede6-4ffc-b1e0-cf7b505186a3)
Sample pattern of Floyd's Triangle for n=5

**Comment by nazeer-18** [comment]
Assigned!! @pranee17

**Comment by pranee17** [comment]
done🤝
