### ISSUE TITLE
0-1 Triangle Pattern

### ISSUE THREAD

**Issue by pranee17** [nazeer-18/java#13]
**Is your feature request related to a problem? Please describe.**
I've found an issue about patterns and would like to contribute for it

**Describe the solution you'd like**
If you assign this issue to me ,I'll add solution for 0-1 Triangle Pattern in java language

**Describe alternatives you've considered**
I've already added some patterns so, I will ensure to follow the same structure for this pattern too

**Additional context**
![image](https://github.com/nazeer-18/java/assets/120731376/9b7c0cde-9ad6-4848-8f97-f4796a4a3d20)
Sample pattern of 0-1 Triangle for n=5

**Comment by nazeer-18** [comment]
Assigned!! @pranee17

**Comment by pranee17** [comment]
completed🙌
