### ISSUE TITLE
Hollow Rhombus Pattern

### ISSUE THREAD

**Issue by pranee17** [nazeer-18/java#15]
**Is your feature request related to a problem? Please describe.**
I've found an issue about patterns and would like to contribute for it

**Describe the solution you'd like**
If you assign this issue to me ,I'll add solution for Hollow Rhombus Pattern in java language

**Describe alternatives you've considered**
I've already added some patterns so, I will ensure to follow the same structure for this pattern too

**Additional context**
![image](https://github.com/nazeer-18/java/assets/120731376/ef1b48b1-17fc-48a2-87e0-6a42881a69fe)
Sample pattern of Hollow Rhombus for n=6

**Comment by nazeer-18** [comment]
Assigned! @pranee17

**Comment by pranee17** [comment]
completed
