### ISSUE TITLE
Diamond Pattern

### ISSUE THREAD

**Issue by pranee17** [nazeer-18/java#16]
**Is your feature request related to a problem? Please describe.**
I've found an issue about patterns and would like to contribute for it

**Describe the solution you'd like**
If you assign this issue to me ,I'll add solution for Diamond Pattern in java language

**Describe alternatives you've considered**
I've already added some patterns so, I will ensure to follow the same structure for this pattern too

**Additional context**
![image](https://github.com/nazeer-18/java/assets/120731376/61ff6328-b2e4-494c-a5bb-5c3b25b1899b)
Sample pattern of Diamond  for n=4

**Comment by nazeer-18** [comment]
Good issue 🧠
Assigned !

**Comment by pranee17** [comment]
Thankyou
