### ISSUE TITLE
Arrays 

### ISSUE THREAD

**Issue by pranee17** [nazeer-18/java#18]
**Is your feature request related to a problem? Please describe.**
After going through your Github , I would like to Contribute for Arrays

**Describe the solution you'd like**
If you assign this issue to me , I'll add Basics of Arrays  like declaration , instantiation, initialization  in java language

**Describe alternatives you've considered**
I've already gone through the structure of other directories in this repo and I will ensure to follow the same structures for Arrays

**Comment by nazeer-18** [comment]
ok assigned!

**Comment by pranee17** [comment]
ThankYou 🤗
