### ISSUE TITLE
Butterfly pattern

### ISSUE THREAD

**Issue by pranee17** [nazeer-18/java#4]
**Is your feature request related to a problem? Please describe.**
After going through your Github I've found an issue about patterns and  would like to contribute for it

**Describe the solution you'd like**
 If you assign this issue to me ,I'll add solution for Butterfly Pattern  in java language

**Describe alternatives you've considered**
I've already gone through the structure of other directories in this repo and I will ensure to follow the same structures  for patterns

**Additional context**
![image](https://github.com/nazeer-18/java/assets/120731376/c8d60bd8-0e70-43fc-a19a-6b73e95cdad1)
   This is a sample of  Butterfly pattern for n=4
 Can you please assign this issue to me @nazeer-18 ?

**Comment by nazeer-18** [comment]
assigned !! Please try to complete this within a week.

**Comment by pranee17** [comment]
> assigned !! Please try to complete this within a week.

Definitely 👍
