### ISSUE TITLE
Hollow Rectangle Pattern

### ISSUE THREAD

**Issue by pranee17** [nazeer-18/java#7]
**Is your feature request related to a problem? Please describe.**
 I've found an issue about patterns and would like to contribute for it
**Describe the solution you'd like**
If you assign this issue to me ,I'll add solution for Hollow Rectangle Pattern in java language
**Describe alternatives you've considered**
I've already added butterfly pattern so, I will ensure to follow the same structures for all other patterns
**Additional context**
![WhatsApp Image 2023-07-19 at 11 25 26 PM (1)](https://github.com/nazeer-18/java/assets/120731376/20dd6a50-363c-4f8e-a5d1-106485788cc0)
Sample pattern of hollow rectangle for 5 rows and 6 columns

**Comment by nazeer-18** [comment]
assigned !!

**Comment by pranee17** [comment]
completed
